#!/usr/bin/env python3
"""
formatter.py - Markdown Note Formatting Layer
Uses Jinja2 templates to generate markdown content.
"""

from __future__ import annotations

import re
from datetime import datetime
from pathlib import Path
from typing import Any

from jinja2 import Environment, FileSystemLoader

TEMPLATE_DIR = Path(__file__).parent / "templates"
env = Environment(loader=FileSystemLoader(str(TEMPLATE_DIR)), trim_blocks=True, lstrip_blocks=True)

AI_BUCKET_ORDER = ["前沿技巧", "工程实践", "工具链更新"]


def today_str() -> str:
    return datetime.now().strftime("%Y-%m-%d")


def now_str() -> str:
    return datetime.now().strftime("%Y-%m-%dT%H:%M:%S")


def slugify(text: str) -> str:
    """Convert a title string to a safe filename slug."""
    text = re.sub(r"[^\w\s\-\u4e00-\u9fff]", "", text)
    text = re.sub(r"\s+", "-", text.strip())
    text = text.strip("-_")[:80]
    return text or "untitled"


def _build_ai_bucket_view(
    items_by_source: dict[str, list[dict]],
) -> dict[str, list[tuple[str, dict]]]:
    buckets: dict[str, list[tuple[str, dict]]] = {k: [] for k in AI_BUCKET_ORDER}

    for source, items in items_by_source.items():
        for item in items:
            if item.get("score") is None:
                continue
            bucket = item.get("ai_bucket") or "工程实践"
            if bucket not in buckets:
                bucket = "工程实践"
            buckets[bucket].append((source, item))

    for bucket_name in buckets:
        buckets[bucket_name].sort(
            key=lambda pair: (pair[1].get("score", 0), pair[1].get("title", "")),
            reverse=True,
        )
    return buckets


def _render_ai_bucket_section(
    lines: list[str], ai_buckets: dict[str, list[tuple[str, dict]]]
) -> None:
    lines.append("## AI-News Curated Buckets\n")
    lines.append("*Fixed sections for fast curation: 前沿技巧 / 工程实践 / 工具链更新*\n")

    for bucket in AI_BUCKET_ORDER:
        lines.append(f"### {bucket}\n")
        entries = ai_buckets[bucket]
        if not entries:
            lines.append("- *(empty today)*\n")
            continue

        for source, item in entries:
            lines.append(f"- **Title**: {item['title']}")
            lines.append(f"  **URL**: {item['link']}")
            lines.append(f"  **Source**: {source}")
            lines.append(f"  **InterestScore**: {item.get('score', 0)}")
            if item.get("score_reasons"):
                lines.append(f"  **ScoreSignals**: {', '.join(item['score_reasons'])}")
            if item.get("summary"):
                lines.append(f"  **Summary**: {item['summary'][:500]}")
            lines.append("")


def format_daily_digest(items_by_source: dict, raw_only: bool = False) -> tuple[str, str]:
    """Format a daily digest note and return (filepath, content)."""
    today = today_str()
    ai_buckets = _build_ai_bucket_view(items_by_source)

    if raw_only:
        filepath = f"00-Inbox/Raw-Feeds/Raw-Daily-Feeds-{today}.md"
        lines = [
            f"# Raw Daily Feeds - {today}\n\n"
            "*This file is generated by PKM Workflow for AI-assisted curation.*\n"
        ]

        _render_ai_bucket_section(lines, ai_buckets)

        lines.append("## Source Buckets (Full Raw by Feed)\n")
        for source, items in items_by_source.items():
            lines.append(f"## {source}\n")
            for item in items:
                lines.append(f"- **Title**: {item['title']}")
                lines.append(f"  **URL**: {item['link']}")
                if item.get("score") is not None:
                    lines.append(f"  **InterestScore**: {item['score']}")
                    if item.get("score_reasons"):
                        lines.append(f"  **ScoreSignals**: {', '.join(item['score_reasons'])}")
                if item.get("summary"):
                    lines.append(f"  **Summary**: {item['summary'][:500]}")
                lines.append("")
        content = "\n".join(lines)
    else:
        filepath = f"30-Daily/AI-News/AI-Daily-{today}.md"

        lines = [
            "---",
            f'title: "AI Daily Digest - {today}"',
            f"date: {today}",
            'tags: ["AI-News", "Daily", "Digest"]',
            "type: daily-digest",
            "status: unreviewed",
            f"created: {now_str()}",
            "---",
            "",
            f"# AI Daily Digest - {today}",
            "",
            "## AI-News Curated Buckets",
            "*Fixed sections for fast review: 前沿技巧 / 工程实践 / 工具链更新*",
            "",
        ]

        for bucket in AI_BUCKET_ORDER:
            lines.append(f"### {bucket}")
            entries = ai_buckets[bucket]
            if not entries:
                lines.append("- *(empty today)*")
                lines.append("")
                continue

            for source, item in entries:
                lines.append(f"- **[{item['title']}]({item['link']})**")
                lines.append(f"  Source: {source}")
                lines.append(f"  InterestScore: {item.get('score', 0)}")
                if item.get("summary"):
                    lines.append(f"  > {item['summary'][:200]}...")
                lines.append("")

        lines.append("## Source Buckets (All)")
        lines.append("")
        for source, items in items_by_source.items():
            lines.append(f"## {source}")
            lines.append("")
            for item in items:
                lines.append(f"- **[{item['title']}]({item['link']})**")
                if item.get("summary"):
                    lines.append(f"  > {item['summary'][:200]}...")
                lines.append("")
        content = "\n".join(lines)

    return filepath, content


def format_youtube_raw_block(yt_videos: list) -> str:
    """Format a block of YouTube entries to append to Raw-Daily-Feeds.md."""
    if not yt_videos:
        return ""
    template = env.get_template("youtube_raw_block.md.j2")
    return template.render(videos=yt_videos)


def format_paper_note(paper: dict, source_name: str) -> tuple[str, str]:
    """Format an individual paper note."""
    today = today_str()
    title = paper["title"]
    safe_title = slugify(title)
    filepath = f"20-Sources/Papers/{today}-{safe_title}.md"

    template = env.get_template("paper_note.md.j2")
    content = template.render(
        title=title,
        today=today,
        now=now_str(),
        source_name=source_name,
        link=paper["link"],
        summary=paper["summary"],
    )
    return filepath, content


def format_video_note(video: dict) -> tuple[str, str]:
    """Format an individual YouTube video note."""
    name = video["channel_name"]
    title = video["title"]
    published = video["published"]
    folder = video["folder"]

    safe_title = slugify(title)
    filepath = f"{folder}/{published}-{name.replace(' ', '-')}-{safe_title}.md"

    template = env.get_template("video_note.md.j2")
    content = template.render(
        title=title,
        channel_name=name,
        domain=video["domain"],
        published=published,
        link=video["link"],
        summary=video.get("summary", ""),
        now=now_str(),
    )
    return filepath, content


def format_ielts_reminder() -> tuple[str, str]:
    """Format a daily IELTS study log note."""
    today = today_str()
    filepath = f"10-Notes/IELTS/IELTS-Study-{today}.md"

    template = env.get_template("study_log.md.j2")
    content = template.render(today=today, now=now_str())
    return filepath, content


def build_note(
    title: str,
    content: str,
    tags: list,
    domain: str,
    source: str = "User Content",
    language: str = "cn",
    note_type: str = "permanent-note",
    related: list[Any] | None = None,
    status: str = "unreviewed",
    core_concept: str = "",
    entity_type: str = "concept",
    source_count: int = 1,
    sources: list[str] | None = None,
) -> str:
    """Build a complete Markdown PKM note string via Generic Template."""
    related = related or []
    sources = [s for s in (sources or []) if s]
    if not sources and source:
        sources = [source]
    source_count = max(source_count, len(sources))

    template = env.get_template("generic_note.md.j2")
    return template.render(
        title=title,
        today=today_str(),
        now=now_str(),
        tags=tags,
        domain=domain,
        status=status,
        core_concept=core_concept,
        entity_type=entity_type,
        source=source,
        source_count=source_count,
        sources=sources,
        language=language,
        note_type=note_type,
        related=related,
        content=content,
    )
